import path from 'node:path'
import {defineConfig} from 'vitest/config'

const aliasObj = {
	'@main': path.resolve('src/main'),
	'@preload': path.resolve('src/preload'),
	'@renderer': path.resolve('src/renderer/src'),
	'@shared': path.resolve('src/shared'),
	'yt-dlp-bridge/parsers': path.resolve('packages/yt-dlp-bridge/src/parsers.ts'),
	'yt-dlp-bridge/redaction': path.resolve('packages/yt-dlp-bridge/src/redaction.ts'),
	'yt-dlp-bridge': path.resolve('packages/yt-dlp-bridge/src/index.ts'),
	'ytdlp-errors': path.resolve('packages/ytdlp-errors/src/index.ts'),
	'electron-log/main.js': path.resolve('tests/__mocks__/electron-log-main.ts'),
	'electron-log/renderer.js': path.resolve('tests/__mocks__/electron-log-renderer.ts'),
	electron: path.resolve('tests/__mocks__/electron.ts')
}

// `unplugin-icons` virtual modules (`~icons/simple-icons/x`,
// `~icons/logos/facebook`, etc.) are generated by the Vite plugin at build
// time. Vitest doesn't run that plugin — without a regex alias, every test
// that transitively imports ShareDialog crashes on import resolution. Map
// every `~icons/*` to a single inert SVG stub.
const alias = [...Object.entries(aliasObj).map(([find, replacement]) => ({find, replacement})), {find: /^~icons\/.*/, replacement: path.resolve('tests/__mocks__/icons-stub.tsx')}]

// Vitest defaults to 5s, which is not enough headroom on the Windows CI runner.
// A good number of the node tests do real filesystem work in `os.tmpdir()` —
// mkdtemp, write, then hash the bytes back — and on Windows every one of those
// touches goes through the virus scanner before it returns. Locally those tests
// finish in milliseconds; on a contended runner one of them occasionally walks
// past 5s and fails as a timeout with nothing actually wrong. 20s still catches
// a genuinely hung test quickly enough to be useful.
const TIMEOUT_MS = 20_000

export default defineConfig({
	test: {
		projects: [
			{resolve: {alias}, test: {name: 'node', globals: true, include: ['tests/**/*.test.ts'], environment: 'node', setupFiles: ['tests/setup.ts'], testTimeout: TIMEOUT_MS, hookTimeout: TIMEOUT_MS}},
			{resolve: {alias}, test: {name: 'jsdom', globals: true, include: ['tests/**/*.test.tsx'], environment: 'jsdom', setupFiles: ['tests/setup.ts'], testTimeout: TIMEOUT_MS, hookTimeout: TIMEOUT_MS}}
		]
	}
})
