name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get latest release tag
        id: get_latest
        uses: actions/github-script@v9
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput("tag", latest.data.tag_name);

      - uses: vedantmgoyal9/winget-releaser@b3a5dae0047c6180023acba3f548c55fdf6b7193
        with:
          identifier: AntonioOrionus.Arroxy
          installers-regex: '^Arroxy-win-x64-Setup\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ steps.get_latest.outputs.tag }}
          extra-installer-fields: |
            Scope: user
            InstallModes:
            - silent
            - silentWithProgress
