// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/feedback-cards/Current.tsx": () => import("../components/mockups/feedback-cards/Current.tsx"),
  "./components/mockups/feedback-cards/ScrollAndStats.tsx": () => import("../components/mockups/feedback-cards/ScrollAndStats.tsx"),
  "./components/mockups/transactions-page/Current.tsx": () => import("../components/mockups/transactions-page/Current.tsx"),
  "./components/mockups/transactions-page/Refined.tsx": () => import("../components/mockups/transactions-page/Refined.tsx"),
  "./components/mockups/transactions-page/TransactionsPreview.tsx": () => import("../components/mockups/transactions-page/TransactionsPreview.tsx")
};
